// src/tools/index.js

const TOOLS = [
  {
    id: "json",
    label: "JSON Formatter",
    shortLabel: "JSON",
    icon: "{ }",
    path: "/json-formatter",
    description: "Format, validate and beautify JSON data",
    keywords: "json formatter, json validator, json beautifier",
    sampleInput: `{"name":"FormatX","version":1,"features":["fast","free","open"],"active":true}`,
  },
  {
    id: "xml",
    label: "XML Formatter",
    shortLabel: "XML",
    icon: "</>",
    path: "/xml-formatter",
    description: "Format and beautify XML documents",
    keywords: "xml formatter, xml beautifier, xml validator",
    sampleInput: `<root><user id="1"><name>FormatX</name><role>admin</role></user></root>`,
  },
  {
    id: "html",
    label: "HTML Formatter",
    shortLabel: "HTML",
    icon: "<h>",
    path: "/html-formatter",
    description: "Beautify and format HTML markup",
    keywords: "html formatter, html beautifier, html prettify",
    sampleInput: `<div class="card"><h1>Hello</h1><p>Welcome to <strong>FormatX</strong></p></div>`,
  },
  {
    id: "css",
    label: "CSS Formatter",
    shortLabel: "CSS",
    icon: "#{}",
    path: "/css-formatter",
    description: "Format and beautify CSS stylesheets",
    keywords: "css formatter, css beautifier, css prettify",
    sampleInput: `.card{display:flex;flex-direction:column;padding:1rem;background:#fff;border-radius:8px;}`,
  },
  {
    id: "sql",
    label: "SQL Formatter",
    shortLabel: "SQL",
    icon: "DB",
    path: "/sql-formatter",
    description: "Format and beautify SQL queries",
    keywords: "sql formatter, sql beautifier, sql query formatter",
    sampleInput: `select u.id, u.name, count(o.id) as orders from users u left join orders o on u.id = o.user_id where u.active = true group by u.id order by orders desc limit 10`,
  },
  {
    id: "base64",
    label: "Base64 Encoder",
    shortLabel: "Base64",
    icon: "64",
    path: "/base64-encoder",
    description: "Encode and decode Base64 strings",
    keywords: "base64 encoder, base64 decoder, base64 converter",
    sampleInput: `Hello, welcome to FormatX!`,
  },
  {
    id: "url",
    label: "URL Encoder",
    shortLabel: "URL",
    icon: "://",
    path: "/url-encoder",
    description: "Encode and decode URL strings",
    keywords: "url encoder, url decoder, url encode decode",
    sampleInput: `https://formatx.in/search?q=hello world&lang=en`,
  },
  {
    id: "jwt",
    label: "JWT Decoder",
    shortLabel: "JWT",
    icon: "JWT",
    path: "/jwt-decoder",
    description: "Decode and inspect JWT tokens",
    keywords: "jwt decoder, jwt token, jwt inspector",
    sampleInput: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkZvcm1hdFgiLCJpYXQiOjE1MTYyMzkwMjJ9.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c`,
  },
];

export default TOOLS;